"""initial_schema

Revision ID: a34e7a76f341
Revises: 
Create Date: 2026-07-15 15:04:18.642951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a34e7a76f341'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bid_projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=128), nullable=False),
    sa.Column('project_name', sa.String(length=512), nullable=False),
    sa.Column('purchaser', sa.String(length=512), nullable=True),
    sa.Column('procurement_agency', sa.String(length=512), nullable=True),
    sa.Column('procurement_method', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('budget_cny', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price_ceiling_cny', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bid_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'parsing', 'analyzing', 'reviewing', 'completed', 'archived', name='project_status', create_constraint=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bid_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bid_projects'))
    )
    op.create_index(op.f('ix_bid_projects_organization_id'), 'bid_projects', ['organization_id'], unique=False)
    op.create_index('ix_bid_projects_organization_id_status', 'bid_projects', ['organization_id', 'status'], unique=False)
    op.create_index('ix_bid_projects_project_code', 'bid_projects', ['project_code'], unique=False)
    op.create_index(op.f('ix_bid_projects_status'), 'bid_projects', ['status'], unique=False)
    op.create_table('company_profiles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('credit_code', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_company_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_profiles'))
    )
    op.create_index('ix_company_profiles_credit_code', 'company_profiles', ['credit_code'], unique=False)
    op.create_index('ix_company_profiles_organization_id', 'company_profiles', ['organization_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'manager', 'member', 'reviewer', name='member_role', create_constraint=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['bid_projects.id'], name=op.f('fk_conversations_project_id_bid_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index('ix_conversations_organization_id_project_id', 'conversations', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('tender', 'announcement', 'amendment', 'result', 'contract', 'company_profile', 'qualification', 'case', 'personnel', 'product', 'other', name='document_type', create_constraint=True), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'success', 'partial', 'failed', name='parse_status', create_constraint=True), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['bid_projects.id'], name=op.f('fk_documents_project_id_bid_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_parse_status'), 'documents', ['parse_status'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index('ix_documents_project_id_document_type', 'documents', ['project_id', 'document_type'], unique=False)
    op.create_index('ix_documents_sha256', 'documents', ['sha256'], unique=False)
    op.create_table('agent_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'waiting_for_user', 'completed', 'failed', 'cancelled', name='agent_run_status', create_constraint=True), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agent_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['bid_projects.id'], name=op.f('fk_agent_runs_project_id_bid_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_conversation_id', 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_organization_id'), 'agent_runs', ['organization_id'], unique=False)
    op.create_index('ix_agent_runs_organization_id_project_id', 'agent_runs', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('clause_id', sa.String(length=128), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('bbox_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['bid_projects.id'], name=op.f('fk_document_chunks_project_id_bid_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_id_chunk_index')
    )
    op.create_index('ix_document_chunks_content_hash', 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_project_id', 'document_chunks', ['project_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_id_version_number')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='message_role', create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('requirements',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('requirement_code', sa.String(length=128), nullable=True),
    sa.Column('category', sa.Enum('project_info', 'qualification', 'commercial', 'technical', 'scoring', 'material', 'deadline', 'mandatory', 'invalid_bid', 'contract', name='requirement_category', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('normalized_requirement', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level', create_constraint=True), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=512), nullable=True),
    sa.Column('source_clause_id', sa.String(length=128), nullable=True),
    sa.Column('evidence_required_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_level', sa.Enum('gold', 'silver', 'pending', name='quality_level', create_constraint=True), nullable=False),
    sa.Column('review_status', sa.Enum('reviewed', 'auto_checked', 'unreviewed', name='review_status', create_constraint=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['bid_projects.id'], name=op.f('fk_requirements_project_id_bid_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_requirements_source_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    op.create_index(op.f('ix_requirements_category'), 'requirements', ['category'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index('ix_requirements_project_id_category', 'requirements', ['project_id', 'category'], unique=False)
    op.create_index('ix_requirements_project_id_risk_level', 'requirements', ['project_id', 'risk_level'], unique=False)
    op.create_index('ix_requirements_requirement_code', 'requirements', ['requirement_code'], unique=False)
    op.create_index('ix_requirements_review_status', 'requirements', ['review_status'], unique=False)
    op.create_index(op.f('ix_requirements_source_document_id'), 'requirements', ['source_document_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps'))
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_index('ix_agent_steps_agent_run_id_step_index', 'agent_steps', ['agent_run_id', 'step_index'], unique=False)
    op.create_table('evidence_links',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_evidence_links_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_links_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_evidence_links_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_links'))
    )
    op.create_index('ix_evidence_links_requirement_id', 'evidence_links', ['requirement_id'], unique=False)
    op.create_table('requirement_matches',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('satisfied', 'partially_satisfied', 'missing', 'uncertain', name='match_status', create_constraint=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risk_level', create_constraint=True), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('quality_level', sa.Enum('gold', 'silver', 'pending', name='quality_level', create_constraint=True), nullable=False),
    sa.Column('review_status', sa.Enum('reviewed', 'auto_checked', 'unreviewed', name='review_status', create_constraint=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], name=op.f('fk_requirement_matches_company_profile_id_company_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_matches_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_matches'))
    )
    op.create_index(op.f('ix_requirement_matches_company_profile_id'), 'requirement_matches', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_requirement_matches_requirement_id'), 'requirement_matches', ['requirement_id'], unique=False)
    op.create_index('ix_requirement_matches_requirement_id_company_profile_id', 'requirement_matches', ['requirement_id', 'company_profile_id'], unique=False)
    op.create_index('ix_requirement_matches_status', 'requirement_matches', ['status'], unique=False)
    op.create_table('requirement_match_evidence',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], name=op.f('fk_requirement_match_evidence_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_requirement_match_evidence_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['requirement_matches.id'], name=op.f('fk_requirement_match_evidence_match_id_requirement_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_match_evidence'))
    )
    op.create_index('ix_requirement_match_evidence_match_id', 'requirement_match_evidence', ['match_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_step_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_tool_calls_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], name=op.f('fk_tool_calls_agent_step_id_agent_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index('ix_tool_calls_agent_run_id', 'tool_calls', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_agent_step_id'), 'tool_calls', ['agent_step_id'], unique=False)
    op.create_index('ix_tool_calls_tool_name', 'tool_calls', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_tool_name', table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_agent_step_id'), table_name='tool_calls')
    op.drop_index('ix_tool_calls_agent_run_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_requirement_match_evidence_match_id', table_name='requirement_match_evidence')
    op.drop_table('requirement_match_evidence')
    op.drop_index('ix_requirement_matches_status', table_name='requirement_matches')
    op.drop_index('ix_requirement_matches_requirement_id_company_profile_id', table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_requirement_id'), table_name='requirement_matches')
    op.drop_index(op.f('ix_requirement_matches_company_profile_id'), table_name='requirement_matches')
    op.drop_table('requirement_matches')
    op.drop_index('ix_evidence_links_requirement_id', table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index('ix_agent_steps_agent_run_id_step_index', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_requirements_source_document_id'), table_name='requirements')
    op.drop_index('ix_requirements_review_status', table_name='requirements')
    op.drop_index('ix_requirements_requirement_code', table_name='requirements')
    op.drop_index('ix_requirements_project_id_risk_level', table_name='requirements')
    op.drop_index('ix_requirements_project_id_category', table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_category'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_chunks_project_id', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_content_hash', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_organization_id_project_id', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_organization_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_conversation_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_documents_sha256', table_name='documents')
    op.drop_index('ix_documents_project_id_document_type', table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_parse_status'), table_name='documents')
    op.drop_index('ix_documents_organization_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index('ix_conversations_organization_id_project_id', table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('ix_company_profiles_organization_id', table_name='company_profiles')
    op.drop_index('ix_company_profiles_credit_code', table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_bid_projects_status'), table_name='bid_projects')
    op.drop_index('ix_bid_projects_project_code', table_name='bid_projects')
    op.drop_index('ix_bid_projects_organization_id_status', table_name='bid_projects')
    op.drop_index(op.f('ix_bid_projects_organization_id'), table_name='bid_projects')
    op.drop_table('bid_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
